CREATE TABLE [dbo].[VehicleListing]
(
	[_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [_URL] VARCHAR(180) NOT NULL, 
    [_Make] VARBINARY(20) NOT NULL, 
    [_Model] VARCHAR(50) NOT NULL, 
    [_ModelConfig] NVARCHAR(50),
    [_Year] INT NOT NULL, 
    [_Price] MONEY NOT NULL, 
    [_Mileage] VARCHAR(20) NULL, 
    [_City] VARCHAR(25) NOT NULL, 
    [_State] VARCHAR(25) NOT NULL, 
    [_Coordinates] VARCHAR(20) NOT NULL, 
    [_PriceStat] NVARCHAR(50) NULL, 
    [_DateAdded] DATE NOT NULL, 
    [_isDealership] VARCHAR(10) NOT NULL, 
    [_Image1] IMAGE NULL, 
    [_Image2] IMAGE NULL, 
    [_Image3] IMAGE NULL, 
    [_Image4] IMAGE NULL, 
    [_Image5] IMAGE NULL, 
    [_Image6] IMAGE NULL, 
    [_Image7] IMAGE NULL, 
    [_Image8] IMAGE NULL, 
    [_Image9] IMAGE NULL, 
    [_Image10] IMAGE NULL, 
    [_Image11] IMAGE NULL, 
    [_Image12] IMAGE NULL, 
    [_ListingDetails] NVARCHAR(200) NULL
)
